# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Determines if label matching is case sensitive (optional). Defaults to true.
caseSensitive: false

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings:
  [x] Audio : Audio
  [x] Video : Video
  [x] Documentation : Documentation
  [x] Android Dev (Flutter): Android-Dev-Java
  [x] Android Dev (Kotlin): Android-Dev-Kotlin
  [x] Android Dev (Java): Android-Dev-Java
  [x] Backend Dev (Java):  Backend-Dev-Java
  [x] Backend Dev (.NET):  .NET
  [x] Backend Dev (PHP):  Backend-Dev-PHP
  [x] Backend Dev (Python): Backend-Dev-Python
  [x] C/CPP : C/CPP
  [x] Competitive Programming : Competitive Programming
  [x] Cyber Security : Cyber Security
  [x] DSA : DSA
  [x] Database : Database
  [x] Datascience with Python : Datascience with Python
  [x] Datascience with R : Datascience with R
  [x] Frontend Dev HTML/CSS/JS : Frontend Dev HTML/CSS/JS
  [x] Frontend Dev React/Angular/Vue : Frontend Dev React/Angular/Vue
  [x] Golang : Golang
  [x] Interview Prep : Interview Prep
  [x] Java_Domain : Java
  [x] JavaScript : JavaScript
  [x] MERN : MERN
  [x] Machine Learning : Machine Learning
  [x] Open Source : Open Source
  [x] Python_Domain : Python
  [x] Rust : Rust
  [x] Statistics : Statistics
  [x] UI/UX : UI/UX
