name: Contributors.md
on: [push]
jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Maanuj-Vora/List-Contributors@1.0.3
        with:
          REPO_NAME: '${{github.repository}}'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTRIBUTOR: '### Contributors'
          FILEPATH: './contributors.md'
          COLUMN_PER_ROW: '5'
          IMG_WIDTH: '50'
